Us22.signup back
WildCodeSchool-2024-02/JS-lyon-0224-P3-ricetrio pull request #37
Opened 2024-06-20 14:33 UTC by Thienthienko

2024-06-20 14:37 UTC, Kana-Fujihira approved these changes
Checked

2024-06-20 14:37 UTC, Kana-Fujihira commented on server/app/controllers/userActions.js
console.info() delete

2024-06-24 12:19 UTC, wildmatthieu requested changes

2024-06-24 12:19 UTC, wildmatthieu commented on server/database/models/UserRepository.js
> +    // Appelle le constructeur de la classe parente (AbstractRepository)
pourquoi des commentaires en fr ici alors que les commentaires sont en anglais partout ailleur ? 
choix à faire => et harmonisation à apporter :)

2024-06-24 12:19 UTC, wildmatthieu commented on server/database/models/UserRepository.js
> +    // Appelle le constructeur de la classe parente (AbstractRepository)
attention il y a d'autres commentaires en fr dans cette page

2024-06-24 12:31 UTC, merged