add carousel
WildCodeSchool-2024-02/JS-lyon-0224-P3-ricetrio pull request #8
Opened 2024-06-06 14:03 UTC by Kana-Fujihira

En tant qu’utilisateur faire défiler un nombre limité de vidéos sélectionnées et pouvoir cliquer dessus
Poker Planning : 7/10

2024-06-06 14:05 UTC, Thienthienko approved these changes
Nice carousel

2024-06-06 14:22 UTC, Thienthienko approved these changes
OK !

2024-06-06 14:23 UTC, kna1703 approved these changes
nice

2024-06-06 14:35 UTC, HazeFury commented on client/package.json
> +    "react-responsive-carousel": "^3.2.23",
bibliothèque pas super à jour et un peu lourde. essayer d'en une trouver mieux ^^

2024-06-06 14:38 UTC, HazeFury commented on client/src/components/Home/MainCarousel.jsx
> +import japan from "../../assets/images/japan.png";
Il faut mettre des majuscules pour les noms d'images.

2024-06-06 14:38 UTC, HazeFury requested changes
2 petites corrections à faire sinon bien 👍

2024-06-11 13:19 UTC, Kana-Fujihira commented
****

2024-06-11 13:28 UTC, kna1703 approved these changes
good

2024-06-11 13:30 UTC, kna1703 commented
> 2 petites corrections à faire sinon bien 👍

faites

2024-06-11 13:31 UTC, Thienthienko approved these changes
Ok

2024-06-11 13:33 UTC, closed without merging